#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "defines.h"

layout (std430, binding = 0)          buffer Buffer1Out { uint buffer1[]; };
layout (std430, binding = 1) readonly buffer Buffer2In  { uint buffer2[]; };

layout (push_constant) uniform PushConstants {
	uint n;
} params;

layout (local_size_x = VK_GROUP_SIZE) in;
void main()
{
	const uint i = workSize2DTo1D(gl_GlobalInvocationID);
	if (i < params.n) {
		buffer1[i] = buffer2[i];
	}
}
