#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "defines.h"

layout (std430, binding = 0) readonly buffer Buffer1In    { uint input_output_values[]; };
layout (std430, binding = 1)          buffer Buffer2Out   { uint block_sums[]; };

layout (push_constant) uniform PushConstants {
	uint n;
} params;

shared uint bins[BINS_CNT];

layout (local_size_x = VK_GROUP_SIZE) in;
void main()
{
	const uint thread_ind = gl_LocalInvocationID.x;

	if (thread_ind < BINS_CNT) {
		bins[thread_ind] = input_output_values[thread_ind];
	}
	barrier();

	if (thread_ind == 0u) {
		uint acc = 0u;
		for (uint i = 0u; i < BINS_CNT; ++i) {
			const uint cur = bins[i];
			bins[i] = acc;
			acc += cur;
		}
	}
	barrier();

	if (thread_ind < BINS_CNT) {
		block_sums[thread_ind] = bins[thread_ind];
	}
}
