#version 450

#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable

#include <libgpu/vulkan/vk/common.vk>

#include "defines.h"

layout (std430, binding = 0) readonly buffer Buffer1In  { uint input_values[]; };
layout (std430, binding = 1)          buffer Buffer2Out { uint block_hist[]; };

layout (push_constant) uniform PushConstants {
	uint shift;
	uint n;
} params;

shared uint warp_hist[(VK_GROUP_SIZE >> WARP_LG) * BINS_CNT];

layout (local_size_x = VK_GROUP_SIZE) in;
void main()
{
	const uint global_ind = workSize2DTo1D(gl_GlobalInvocationID);
	const uint thread_ind = gl_LocalInvocationID.x;
	const uint block_ind = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;
	const uint warp_ind = thread_ind >> WARP_LG;
	const uint lane_ind = thread_ind & (VK_SUBGROUP_SIZE - 1u);

	if (thread_ind < ((VK_GROUP_SIZE >> WARP_LG) * BINS_CNT)) {
		warp_hist[thread_ind] = 0u;
	}
	barrier();

	const bool is_active = global_ind < params.n;
	const uint bin = is_active ? ((input_values[global_ind] >> params.shift) & RADIX_MASK) : 0u;
	for (uint b = 0u; b < BINS_CNT; ++b) {
		uvec4 mask = subgroupBallot(is_active && bin == b);
		if (lane_ind == b) {
			warp_hist[(warp_ind << BITS_AT_A_TIME) + b] = subgroupBallotBitCount(mask);
		}
	}
	barrier();

	if (thread_ind < BINS_CNT) {
		uint sum = 0u;
		for (uint warp = 0u; warp < (VK_GROUP_SIZE >> WARP_LG); ++warp) {
			sum += warp_hist[(warp << BITS_AT_A_TIME) + thread_ind];
		}
		block_hist[thread_ind + block_ind * BINS_CNT] = sum;
	}
}
